version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: josedhonatas
      POSTGRES_DB: product
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
